# Generated by Django 3.1.2 on 2021-01-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_writer_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='idUser',
            new_name='id_user',
        ),
    ]
