# Generated by Django 3.1.5 on 2021-01-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('ACT', 'Accepted'), ('RJT', 'Rejected')], max_length=20),
        ),
    ]
