# Generated by Django 3.1.5 on 2021-01-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210125_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('ACT', 'Accepted'), ('RJT', 'Rejected')], default='PD', max_length=20),
        ),
    ]
